In [1]:
#kutuphane
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

veriler = pd.read_csv('dataa.csv')

# preprocessing
print(veriler)

boy= veriler[['boy']]

print(boy)

boykilo= veriler[['boy','kilo']]

print(boykilo)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k
    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166
    boy  kilo
0   130    30
1   125    36
2   135    34
3

In [2]:
# eksik veriler

eksikveriler = pd.read_csv('eksikData.csv')

print(eksikveriler)

# yaş kolonundaki eksik verileri yaş ortalaması ile değiştiriyorum
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

Yas = eksikveriler.iloc[:,1:4].values

print(Yas)

imputer = imputer.fit(Yas[:,1:4])

Yas[:,1:4] = imputer.transform(Yas[:,1:4])
print(Yas)

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k
[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [

In [3]:
# kategorik veriler - encoding

# tr us fr 0 ve 1 olarak encode etme

ulke = veriler.iloc[:,0:1].values

print(ulke)

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

ulke[:,0]= le.fit_transform(veriler.iloc[:,0])

print(ulke)

ohe= preprocessing.OneHotEncoder()

ulke= ohe.fit_transform(ulke).toarray()

print(ulke)


sonuc = pd.DataFrame(data=ulke, index = range(22),columns = ['fr','tr','us'])

print(sonuc)

sonuc2 = pd.DataFrame(data=Yas, index = range(22), columns= ['boy','kilo','yas'])

print(sonuc2)

cinsiyet = veriler.iloc[:,1].values

print(cinsiyet)

sonuc3 = pd.DataFrame(data = cinsiyet, index = range(22), columns = ['cinsiyet'])

print(sonuc3)

s = pd.concat([sonuc,sonuc2], axis = 1)

print(s)

s2 = pd.concat([s,sonuc3],axis=1)

print(s2) #sayısal değerlere impute edildi

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0
      boy   kilo    yas
0   130.0

In [4]:
# bölme işlemi 

from sklearn.model_selection import train_test_split

x_train , x_test,y_train, y_test = train_test_split(s,sonuc3,test_size=0.33,random_state=0)

In [ ]:
# öznitelik ölçekleme

from sklearn.preprocessing import StandardScaler

sc = StandartScaler()

X_train = sc.fit_transform(x_train)

X_test = sc.fit_transform(x_test)